### ISSUE TITLE
Anzeigen der Daten auf einem Display

### ISSUE THREAD

**Issue by Momoshikimi** [Momoshikimi/MQTT-Aufgabe-#6]

**Comment by Diego-Moreira-nr** [comment]
Daten die angezeigt werden sollen sind:

- Datum und Uhrzeit 
- Gebäude mit Raum
- Anwesenheit -> Licht An/Aus
- Temparatur mit °C -> Klimaanlage An/Aus 


Dafür Adafruit_ILI9341 Bibliothek hinzufügen und das Display am Anfang initialisieren. 

Für die Anzeige eine neue void Methode entworfen namens displayData() und diese in unserem Loop aufrufen 

In der Methode werden aus dem JsonString die Daten extrahiert und genutzt für die Anzeige

**Comment by Diego-Moreira-nr** [comment]
Die Methode displayData() nimmt den JsonString welchen wir durch die Methode createJson() bekomme und lösen diesen wieder in unserer Methode auf und zeigen dann die Daten auf unserem ILI9341 Display an

**Comment by Diego-Moreira-nr** [comment]
Getestet wurde es durchs kompilieren und starten des Programmes. Die Daten aus der Json wurden auf dem Bildschirm angezeigt

**Comment by Diego-Moreira-nr** [comment]
Ebenfalls wurde mit der NTPClient Bibliothek das Datum und die Uhrzeit sich geholt, in die .json Datei reingeschrieben und ebenfalls auf dem Bildschirm angezeigt
